/**
 * MLC ERP - Email Notification & Templating Engine
 * Implements shiny Blue & Gold branded responsive templates, exact interview/offer formatting,
 * daily quota checking, PDF attachment handling, and audit logging into EmailLog.
 */

/**
 * Branded HTML Email Container Wrapper
 */
function wrapEmailTemplate(title, bodyContent, actionBtn) {
  var instName = CONFIG.getInstituteName();
  var btnHtml = '';
  if (actionBtn && actionBtn.text && actionBtn.url) {
    btnHtml = '<div style="text-align:center; margin: 30px 0;">' +
      '<a href="' + actionBtn.url + '" style="background: linear-gradient(135deg,#C9930A,#F5B921 45%,#FFE08A 70%,#F5B921); color: #061B4D; font-weight: bold; text-decoration: none; padding: 14px 28px; border-radius: 8px; display: inline-block; box-shadow: 0 4px 12px rgba(245,185,33,0.3);">' +
      actionBtn.text +
      '</a>' +
      '</div>';
  }

  return '<!DOCTYPE html>' +
    '<html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>' +
    '<body style="margin: 0; padding: 0; background-color: #F4F7FD; font-family: -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Helvetica, Arial, sans-serif; color: #0B1530;">' +
    '<table width="100%" border="0" cellspacing="0" cellpadding="0" style="background-color: #F4F7FD; padding: 30px 10px;">' +
    '<tr><td align="center">' +
    '<table width="100%" max-width="600" style="max-width: 600px; background-color: #ffffff; border-radius: 14px; overflow: hidden; box-shadow: 0 8px 24px rgba(6,27,77,0.08); border-top: 4px solid #F5B921;">' +
    // Branded Header
    '<tr><td style="background: linear-gradient(135deg,#061B4D,#0B5FFF 60%,#5B9BFF); padding: 28px 30px; text-align: center;">' +
    '<div style="color: #FFE08A; font-size: 11px; letter-spacing: 2px; text-transform: uppercase; font-weight: bold; margin-bottom: 6px;">' + instName + '</div>' +
    '<h1 style="color: #ffffff; font-size: 22px; margin: 0; font-weight: 700;">' + title + '</h1>' +
    '</td></tr>' +
    // Body
    '<tr><td style="padding: 32px 30px; font-size: 15px; line-height: 1.6; color: #0B1530;">' +
    bodyContent +
    btnHtml +
    '</td></tr>' +
    // Footer
    '<tr><td style="background-color: #F8FAFC; padding: 20px 30px; text-align: center; border-top: 1px solid #E2E8F0; font-size: 12px; color: #64748B;">' +
    '<p style="margin: 0 0 6px 0; font-weight: bold; color: #061B4D;">' + instName + '</p>' +
    '<p style="margin: 0;">Kerala, India | Official Operations & Placement Desk</p>' +
    '<p style="margin: 6px 0 0 0; font-size: 11px; color: #94A3B8;">This is an automated administrative notification generated by MLC ERP.</p>' +
    '</td></tr>' +
    '</table></td></tr></table></body></html>';
}

/**
 * Dispatch Email with Quota Verification & Logging
 */
function sendEmailWithLog(toEmail, subject, htmlBody, attachments, templateName, senderEmail, senderName) {
  if (!toEmail) return { ok: false, error: 'Recipient email missing' };

  var quota = MailApp.getRemainingDailyQuota();
  if (quota <= 0) {
    insertRecord('EmailLog', {
      recipient_email: toEmail,
      template_name: templateName,
      subject: subject,
      status: 'FAILED_QUOTA',
      error_message: 'Daily Gmail sending quota exhausted',
      sent_at: ''
    }, 'SYSTEM');
    return { ok: false, error: 'Gmail daily sending quota exhausted' };
  }

  try {
    var fromName = senderName || CONFIG.getSenderName();
    var replyToEmail = senderEmail || CONFIG.getPlacementSenderEmail();

    var mailOptions = {
      to: toEmail,
      subject: subject,
      htmlBody: htmlBody,
      name: fromName,
      replyTo: replyToEmail
    };

    // If alias is registered in the deploying Gmail account, specify 'from'
    if (senderEmail) {
      try {
        var aliases = GmailApp.getAliases ? GmailApp.getAliases() : [];
        if (aliases.indexOf(senderEmail) !== -1) {
          mailOptions.from = senderEmail;
        }
      } catch (aliasErr) {
        // Fallback to replyTo + display name
      }
    }

    if (attachments && attachments.length) {
      mailOptions.attachments = attachments;
    }

    MailApp.sendEmail(mailOptions);

    insertRecord('EmailLog', {
      recipient_email: toEmail,
      template_name: templateName,
      subject: subject,
      status: 'SENT',
      error_message: '',
      sent_at: new Date().toISOString()
    }, 'SYSTEM');

    return { ok: true };
  } catch (err) {
    insertRecord('EmailLog', {
      recipient_email: toEmail,
      template_name: templateName,
      subject: subject,
      status: 'ERROR',
      error_message: err.toString(),
      sent_at: ''
    }, 'SYSTEM');
    return { ok: false, error: err.toString() };
  }
}

/**
 * 1. Agreement Email with PDF
 */
function sendAgreementEmail(student, pdfUrl, pdfBlob) {
  var subject = 'Signed Training Agreement Confirmation — ' + student.admission_no;
  var body = '<p>Dear <b>' + student.full_name + '</b>,</p>' +
    '<p>Welcome to Mastered Skill Academy! Your official training agreement has been processed, verified, and safely archived into our registry.</p>' +
    '<p>Please find attached your verified agreement copy for your personal records.</p>' +
    '<div style="background-color: #F1F5F9; border-left: 4px solid #0B5FFF; padding: 12px 16px; margin: 20px 0; border-radius: 4px;">' +
    '<b>Admission Number:</b> ' + student.admission_no + '<br/>' +
    '<b>Course:</b> ' + student.course_code + '<br/>' +
    '<b>Status:</b> Agreement Registered & Active' +
    '</div>' +
    '<p>Next Step: Your placement coordinator will be in touch to record your career preferences.</p>';

  var html = wrapEmailTemplate('Training Agreement Confirmation', body, pdfUrl ? { text: 'View Document in Drive', url: pdfUrl } : null);
  var attachments = pdfBlob ? [pdfBlob] : [];
  var targetEmail = student.personal_email || student.professional_email;

  return sendEmailWithLog(targetEmail, subject, html, attachments, 'AGREEMENT_CONFIRMATION');
}

/**
 * 2. Preference Confirmation Email (Sent from Placement Cell: masteredplacements@gmail.com)
 */
function sendPreferenceConfirmationEmail(student, prefRecord, profEmail) {
  var subject = 'Placement Preference Confirmation & Professional Email Verification';
  var body = '<p>Dear <b>' + student.full_name + '</b>,</p>' +
    '<p>Your career preferences have been officially logged with our Placement Cell. Please carefully review the registered preferences below:</p>' +
    '<table width="100%" style="border-collapse: collapse; margin: 20px 0; font-size: 14px;">' +
    '<tr style="background-color: #061B4D; color: #fff;"><th style="padding: 8px 12px; text-align: left;">Preferred Locations</th><th style="padding: 8px 12px; text-align: left;">Target Job Roles</th></tr>' +
    '<tr style="background-color: #F8FAFC;"><td style="padding: 8px 12px; border-bottom: 1px solid #E2E8F0;">1. ' + prefRecord.location_1 + '</td><td style="padding: 8px 12px; border-bottom: 1px solid #E2E8F0;">1. ' + prefRecord.role_1 + '</td></tr>' +
    '<tr><td style="padding: 8px 12px; border-bottom: 1px solid #E2E8F0;">2. ' + prefRecord.location_2 + '</td><td style="padding: 8px 12px; border-bottom: 1px solid #E2E8F0;">2. ' + prefRecord.role_2 + '</td></tr>' +
    '<tr style="background-color: #F8FAFC;"><td style="padding: 8px 12px;">3. ' + prefRecord.location_3 + '</td><td style="padding: 8px 12px;">3. ' + prefRecord.role_3 + '</td></tr>' +
    '</table>' +
    '<div style="background-color: #FEF3C7; border: 1px solid #F59E0B; padding: 14px; border-radius: 8px; margin: 20px 0;">' +
    '<b style="color: #92400E;">Verified Professional Email:</b> <span style="font-family: monospace; font-weight: bold; color: #061B4D;">' + profEmail + '</span>' +
    '<p style="margin: 6px 0 0 0; font-size: 13px; color: #78350F;">Important: All interview call letters, schedules, and recruiter communications will be dispatched strictly to this address.</p>' +
    '</div>';

  var html = wrapEmailTemplate('Placement Preferences Confirmed', body);
  return sendEmailWithLog(
    profEmail,
    subject,
    html,
    [],
    'PREFERENCE_CONFIRMATION',
    CONFIG.getPlacementSenderEmail(),
    CONFIG.getPlacementSenderName()
  );
}

/**
 * 3. Interview Scheduled Email (Sent from Placement Cell: masteredplacements@gmail.com)
 */
function sendInterviewEmail(student, details) {
  var subject = 'Interview Call Scheduled — ' + details.company + ' (' + details.position + ')';
  var exactText = 'Company: ' + details.company + '\n' +
    'Position: ' + details.position + '\n' +
    'Location: ' + details.location + '\n' +
    'Interview Date: ' + details.interview_date + '\n' +
    'Interview Time: ' + details.interview_time;

  var body = '<p>Dear <b>' + student.full_name + '</b>,</p>' +
    '<p>You have been shortlisted for an upcoming interview opportunity through the Placement Cell.</p>' +
    '<div style="background-color: #EFF6FF; border: 2px solid #0B5FFF; border-radius: 8px; padding: 18px; margin: 24px 0; font-family: monospace; font-size: 14px; line-height: 1.8; color: #061B4D;">' +
    'Company: <b>' + details.company + '</b><br/>' +
    'Position: <b>' + details.position + '</b><br/>' +
    'Location: <b>' + details.location + '</b><br/>' +
    'Interview Date: <b>' + details.interview_date + '</b><br/>' +
    'Interview Time: <b>' + details.interview_time + '</b>' +
    '</div>' +
    '<p>Please ensure you are dressed in formal business attire and carry copies of your updated resume.</p>';

  var html = wrapEmailTemplate('Interview Scheduled', body);
  var targetEmail = student.professional_email || student.personal_email;
  return sendEmailWithLog(
    targetEmail,
    subject,
    html,
    [],
    'INTERVIEW_SCHEDULED',
    CONFIG.getPlacementSenderEmail(),
    CONFIG.getPlacementSenderName()
  );
}

/**
 * 4. Job Offer Email (Sent from Placement Cell: masteredplacements@gmail.com)
 */
function sendOfferEmail(student, details) {
  var subject = 'Congratulations! Job Offer Received — ' + details.company;
  var body = '<p>Dear <b>' + student.full_name + '</b>,</p>' +
    '<p>Hearty congratulations on your outstanding achievement! We are delighted to formally notify you of your job offer.</p>' +
    '<div style="background-color: #ECFDF5; border: 2px solid #10B981; border-radius: 8px; padding: 18px; margin: 24px 0; font-family: monospace; font-size: 14px; line-height: 1.8; color: #064E3B;">' +
    'Company: <b>' + details.company + '</b><br/>' +
    'Position: <b>' + details.position + '</b><br/>' +
    'Location: <b>' + details.location + '</b><br/>' +
    'Offer Date: <b>' + details.offer_date + '</b><br/>' +
    'Joining Date: <b>' + details.joining_date + '</b>' +
    '</div>' +
    '<p>We wish you immense success in your professional journey ahead!</p>';

  var html = wrapEmailTemplate('Job Offer Congratulations', body);
  var targetEmail = student.professional_email || student.personal_email;
  return sendEmailWithLog(
    targetEmail,
    subject,
    html,
    [],
    'JOB_OFFER',
    CONFIG.getPlacementSenderEmail(),
    CONFIG.getPlacementSenderName()
  );
}

/**
 * 5. Fee Receipt Email
 */
function sendReceiptEmail(student, payment, installment) {
  var subject = 'Fee Payment Receipt — ' + payment.receipt_no;
  var body = '<p>Dear <b>' + student.full_name + '</b>,</p>' +
    '<p>We have successfully received and acknowledged your fee payment with details below:</p>' +
    '<div style="background-color: #F8FAFC; border: 1px solid #CBD5E1; border-radius: 8px; padding: 18px; margin: 20px 0; font-size: 14px;">' +
    '<table width="100%" cellpadding="4">' +
    '<tr><td><b>Receipt Number:</b></td><td style="font-family: monospace; font-weight: bold; color: #0A3FB5;">' + payment.receipt_no + '</td></tr>' +
    '<tr><td><b>Installment:</b></td><td>' + installment.title + '</td></tr>' +
    '<tr><td><b>Amount Paid:</b></td><td><b style="color: #059669; font-size: 16px;">' + formatINR(payment.amount) + '</b></td></tr>' +
    '<tr><td><b>Payment Mode:</b></td><td>' + payment.payment_mode + '</td></tr>' +
    '<tr><td><b>Transaction Reference:</b></td><td>' + (payment.reference_no || 'N/A') + '</td></tr>' +
    '<tr><td><b>Payment Date:</b></td><td>' + new Date(payment.payment_date).toLocaleDateString('en-IN') + '</td></tr>' +
    '</table>' +
    '</div>' +
    '<p>Thank you for your timely payment. You can access your full fee ledger anytime via the Student Portal.</p>';

  var html = wrapEmailTemplate('Fee Payment Receipt', body);
  var targetEmail = student.personal_email || student.professional_email;
  return sendEmailWithLog(targetEmail, subject, html, [], 'FEE_RECEIPT');
}
